# In _config.yml
title: Linear Regression with Python
author: Vince Maina
# logo: logo.png
execute:
  execute_notebooks: force

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#   - references.bib